apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-providers-azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-sc
  resources:
    requests:
      storage: 100M